name: plantagochi
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1

  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.6.1

  flame: ^1.32.0
  audioplayers: ^6.0.0
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    # Game Character Assets
    - assets/images/sunflower.png
    - assets/images/background/sample.jpg
    - assets/images/background/sunflower_bg.png

    # Mini Game Character Animation Assets
    - assets/images/games/raincatcher.png
    - assets/images/games/raindrops.png
    - assets/images/games/aciddrop.png
    - assets/images/games/goodheart.png
    - assets/images/games/retrybutton.png
    - assets/images/games/GAME OVER.png
    - assets/images/games/GAME COMPLETED.png
    - assets/images/games/proceed.png
    - assets/images/games/WATER METER.png
    - assets/images/games/moving_bg.mp4

    # Mini Game Audio Assets
    - assets/sfx/acid_catch.mp3
    - assets/sfx/water_catch.mp3
    - assets/sfx/water_mini_game_bg.mp3
