// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFpqW5a5v3kkfmD28_BIu9iySJvpJM1mo',
    appId: '1:978316207973:web:73719937e8f8178a43e38c',
    messagingSenderId: '978316207973',
    projectId: 'plant-agochi',
    authDomain: 'plant-agochi.firebaseapp.com',
    storageBucket: 'plant-agochi.firebasestorage.app',
    measurementId: 'G-K5BS0EJ208',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCSE2JfA680BSTfwmmc9bYmut0299cyEk',
    appId: '1:978316207973:android:edf2c38f4eca581043e38c',
    messagingSenderId: '978316207973',
    projectId: 'plant-agochi',
    storageBucket: 'plant-agochi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQe-2akU2NxrUhXYUZ5rFlt5mfBvaT1C4',
    appId: '1:978316207973:ios:08847dd566e2702f43e38c',
    messagingSenderId: '978316207973',
    projectId: 'plant-agochi',
    storageBucket: 'plant-agochi.firebasestorage.app',
    iosBundleId: 'com.example.plantagochi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQe-2akU2NxrUhXYUZ5rFlt5mfBvaT1C4',
    appId: '1:978316207973:ios:08847dd566e2702f43e38c',
    messagingSenderId: '978316207973',
    projectId: 'plant-agochi',
    storageBucket: 'plant-agochi.firebasestorage.app',
    iosBundleId: 'com.example.plantagochi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFpqW5a5v3kkfmD28_BIu9iySJvpJM1mo',
    appId: '1:978316207973:web:aa14287daf940d4243e38c',
    messagingSenderId: '978316207973',
    projectId: 'plant-agochi',
    authDomain: 'plant-agochi.firebaseapp.com',
    storageBucket: 'plant-agochi.firebasestorage.app',
    measurementId: 'G-9WN07KTDZH',
  );
}
